export const productActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
